version: '3.9'
services:
  auth_agent:
    build: ./auth_agent
    container_name: auth_agent
    ports:
      - "8100:8000"
    networks:
      - agents_net

  webservice_agent:
    build: ./webservice_agent
    container_name: webservice_agent
    ports:
      - "8101:8000"
    networks:
      - agents_net
    depends_on:
      - dbservice_agent  # webservice might call dbservice
      - a2a_registry

  dbservice_agent:
    build: ./dbservice_agent
    container_name: dbservice_agent
    ports:
      - "8102:8000"
    networks:
      - agents_net
    volumes:
      - ./dbservice_agent/data:/app/data
    depends_on:
      - a2a_registry

  fake_auth_service:
    build: ./fake_auth_service
    container_name: fake_auth_service
    ports:
      - "8103:8000"
    networks:
      - agents_net
    depends_on:
      - a2a_registry

  a2a_registry:
    build: ./a2a_registry
    container_name: a2a_registry
    ports:
      - "8104:8000"
    networks:
      - agents_net
    volumes:
      - ./a2a_registry/data:/app/data

  webcrawler_agent:
    build: ./webcrawler_agent
    container_name: webcrawler_agent
    ports:
      - "8106:8080"
    networks:
      - agents_net
    depends_on:
      - a2a_registry

  chat_agent:
    build: ./chat_agent
    ports:
      - "8109:8000"
    env_file: .env
    networks:
      - agents_net
    volumes:      
      - ./application_default_credentials.json:/app/application_default_credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json  
    depends_on:
      - a2a_registry
      - query_planner_agent
      - sink_registry_agent

  log_ingest_agent:
    build: ./log_ingest_agent
    container_name: log_ingest_agent
    ports: ["8107:8000"] 
    env_file: .env
    volumes:      
      - ./application_default_credentials.json:/app/application_default_credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json       
      - LOG_ROUTER_URL=http://log_router_agent:8000
    networks: [agents_net]
    depends_on: [a2a_registry]

  log_router_agent:
    build: ./log_router_agent
    container_name: log_router_agent
    ports: ["8108:8000"]
    env_file: .env
    volumes:      
      - ./application_default_credentials.json:/app/application_default_credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json         
    networks: [agents_net]
    depends_on: [a2a_registry]    

  query_planner_agent:
    build: ./query_planner_agent
    ports:
      - "8110:8000"
    env_file: .env
    networks:
      - agents_net
    volumes:      
      - ./application_default_credentials.json:/app/application_default_credentials.json
      - ./dbservice_agent/data:/app/data
    environment:      
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json # <<< ADD THIS
      # Ensure these are defined in your .env file or set directly here
      - GCP_PROJECT_FOR_VERTEX=${GCP_PROJECT_FOR_VERTEX}
      - GCP_LOCATION_FOR_VERTEX=${GCP_LOCATION_FOR_VERTEX}
      - LLM_MODEL_NAME_FOR_QPA=${LLM_MODEL_NAME_FOR_QPA}
      - SINK_REGISTRY_AGENT_URL=http://sink_registry_agent:8000/a2a
    depends_on:
      - a2a_registry
      - sink_registry_agent

  analytics_agent:
    build: ./analytics_agent
    ports:
      - "8111:8000"
    networks:
      - agents_net
    depends_on:
      - a2a_registry

  sink_registry_agent:
    build: ./sink_registry_agent
    ports:
      - "8112:8000"
    networks:
      - agents_net
    volumes:
      - ./sink_registry_agent/data:/app/data   

networks:
  agents_net:
    driver: bridge